name: Check Unity SDK Updates

on:
  push:
    branches:
      - main
  schedule: # Run Daily
    - cron: '0 0 * * *'
  workflow_dispatch:

jobs:
  check-updates:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          token: ${{ secrets.PUBLIC_REPO_BOT_GITHUB_TOKEN }}

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm ci

      - name: Check for AdGem SDK updates
        run: |
          export LATEST_ANDROID_SDK_VERSION=$(npm run check-adgem-version)
          echo "HAS_CHANGES=$(git status --porcelain -z | tr '\0' ' ')" >> "$GITHUB_ENV"
        env:
          GITHUB_TOKEN: ${{ secrets.PUBLIC_REPO_BOT_GITHUB_TOKEN }}

      - name: Commit and push changes
        if: env.HAS_CHANGES
        run: |
          git config --global user.name "${{ vars.BOT_NAME || 'adgem-developers' }}"
          git config --global user.email "${{ vars.BOT_EMAIL || 'developers@adgem.com' }}"
          git add .
          git commit -m 'build: update adgem sdk dependency version'
          git push origin HEAD:refs/heads/update-adgem-sdk-$LATEST_ANDROID_SDK_VERSION

      - name: Create Pull Request
        if: env.HAS_CHANGES
        uses: peter-evans/create-pull-request@v7
        with:
          token: ${{ secrets.PUBLIC_REPO_BOT_GITHUB_TOKEN }}
          branch: update-adgem-sdk-${{ env.LATEST_ANDROID_SDK_VERSION }}
          title: 'build: update adgem sdk dependency version'
          body: | 
            This PR updates the AdGem SDK version to the latest release.
            
            cc: @adgem/sdk-team
          labels: 'automated pr'
          assignees: adgem/sdk-team