name: Check Unity SDK Updates

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

on:
  push:
    branches:
      - main
  schedule: # Run Daily
    - cron: '0 0 * * *'
  workflow_dispatch:

jobs:
  check-updates:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          token: ${{ secrets.ADGEM_SDK_ACTIONS_TOKEN }}

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm ci

      - name: Get latest AdGem Android SDK updates
        env:
          CHECK_TYPE: 'self'
          GITHUB_TOKEN: ${{ secrets.ADGEM_SDK_ACTIONS_TOKEN }}
        run: |
          if ! LATEST_VERSION=$(node ./bin/check-for-updates.js); then
            echo "Error: Failed to get latest SDK version. Please check the script output above for details."
            exit 1
          fi
          echo "LATEST_ANDROID_SDK_VERSION=$LATEST_VERSION" >> "$GITHUB_ENV"
          
          CURRENT_VERSION=$(grep -oP "implementation 'com.adgem.android:adgem-sdk:\K[^']+" AndroidManifest.xml)
          
          echo "HAS_CHANGES=$(LATEST_ANDROID_SDK_VERSION != $CURRENT_VERSION)" >> "$GITHUB_ENV"
          echo "Latest version: $LATEST_VERSION"
          echo "Current version: $CURRENT_VERSION"
          echo "Has changes: $HAS_CHANGES"
      - name: Update Android Manifest File
        if: env.HAS_CHANGES
        run: |
          set -e
          BRANCH_NAME="update-adgem-sdk-${LATEST_ANDROID_SDK_VERSION}-$(date +%s)"
          
          if ! sed -i "s|implementation 'com.adgem.android:adgem-sdk:.*'|implementation 'com.adgem.android:adgem-sdk:${LATEST_ANDROID_SDK_VERSION}'|g" AndroidManifest.xml; then
            echo "Error: Failed to update AndroidManifest.xml"
            exit 1
          fi
      - name: Commit and push changes
        if: env.HAS_CHANGES
        run: |
          git config --global user.name "${{ vars.BOT_NAME || 'adgem-developers' }}"
          git config --global user.email "${{ vars.BOT_EMAIL || 'developers@adgem.com' }}"
          git add .
          git commit -m 'fix(deps): update adgem sdk dependency version'
          git push origin HEAD:refs/heads/update-adgem-sdk-$LATEST_ANDROID_SDK_VERSION

      - name: Create Pull Request
        if: env.HAS_CHANGES
        uses: peter-evans/create-pull-request@v7
        with:
          token: ${{ secrets.ADGEM_SDK_ACTIONS_TOKEN }}
          branch: update-adgem-sdk-${{ env.LATEST_ANDROID_SDK_VERSION }}
          title: 'build: update adgem sdk dependency version'
          delete-branch: true
          body: |
            This PR updates the AdGem SDK version to the latest release.
            
            cc: @adgem/sdk-team

          labels: 'automated pr'
          team-reviewers: adgem/sdk-team